CREATE ROLE remembrancer_role NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE remembrancer LOGIN UNENCRYPTED PASSWORD 'password' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

GRANT remembrancer_role TO remembrancer;

CREATE DATABASE remembrancer WITH OWNER = postgres ENCODING = 'UTF8' CONNECTION LIMIT = -1;
